# Generated by Django 5.0.4 on 2024-04-09 10:36

import django.forms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.forms.fields.EmailField]),
        ),
    ]
